-- Seed initial clinics in London area
INSERT INTO public.clinics (
  name, address, postcode, latitude, longitude, phone, email, website,
  rating, review_count, treatments, price_range, description, facilities,
  opening_hours, featured, verified, accepts_nhs, parking_available, wheelchair_accessible
) VALUES
(
  'Harley Street Dental Studio',
  '45 Harley Street, Marylebone',
  'W1G 8QH',
  51.5186,
  -0.1473,
  '020 7486 2711',
  'info@harleystreetdental.com',
  'https://harleystreetdental.com',
  4.8,
  147,
  ARRAY['Invisalign', 'Veneers', 'Dental Implants', 'Teeth Whitening', 'Composite Bonding'],
  'premium',
  'Award-winning private dental practice in the heart of Harley Street. Specialists in cosmetic dentistry and smile transformations.',
  ARRAY['Digital X-Ray', 'Sedation Available', 'Private Treatment Rooms', 'WiFi', 'Refreshments'],
  '{"monday": "9:00-18:00", "tuesday": "9:00-18:00", "wednesday": "9:00-18:00", "thursday": "9:00-18:00", "friday": "9:00-17:00", "saturday": "10:00-14:00", "sunday": "Closed"}'::jsonb,
  true,
  true,
  false,
  true,
  true
),
(
  'The London Smile Clinic',
  '12 Wimpole Street, Marylebone',
  'W1G 9ST',
  51.5176,
  -0.1487,
  '020 7935 9888',
  'reception@londonsmile.co.uk',
  'https://londonsmile.co.uk',
  4.9,
  203,
  ARRAY['Invisalign', 'Veneers', 'Composite Bonding', 'Teeth Whitening'],
  'premium',
  'Leading cosmetic dental practice specializing in aesthetic treatments and smile makeovers. Over 15 years of excellence.',
  ARRAY['3D Imaging', 'Same-day Veneers', 'Interest-free Finance', 'Digital Smile Design', 'WiFi'],
  '{"monday": "8:00-19:00", "tuesday": "8:00-19:00", "wednesday": "8:00-19:00", "thursday": "8:00-19:00", "friday": "8:00-18:00", "saturday": "9:00-15:00", "sunday": "Closed"}'::jsonb,
  true,
  true,
  false,
  false,
  true
),
(
  'Camden Dental Practice',
  '89 Camden High Street',
  'NW1 7JY',
  51.5396,
  -0.1426,
  '020 7388 5280',
  'info@camdendental.nhs.uk',
  'https://camdendental.co.uk',
  4.5,
  89,
  ARRAY['General Dentistry', 'Dental Implants', 'Teeth Whitening', 'Emergency Care'],
  'mid',
  'Friendly NHS and private practice in Camden. Offering quality dental care for the whole family at affordable prices.',
  ARRAY['NHS Available', 'Emergency Appointments', 'Family Friendly', 'WiFi', 'Ground Floor Access'],
  '{"monday": "9:00-18:00", "tuesday": "9:00-18:00", "wednesday": "9:00-18:00", "thursday": "9:00-20:00", "friday": "9:00-17:00", "saturday": "Closed", "sunday": "Closed"}'::jsonb,
  false,
  true,
  true,
  true,
  true
),
(
  'Shoreditch Dental Studio',
  '156 Shoreditch High Street',
  'E1 6HU',
  51.5255,
  -0.0754,
  '020 7739 4400',
  'hello@shoreditchdental.com',
  'https://shoreditchdental.com',
  4.7,
  124,
  ARRAY['Invisalign', 'Composite Bonding', 'Teeth Whitening', 'General Dentistry', 'Hygienist Services'],
  'mid',
  'Modern dental studio in trendy Shoreditch. Combining cutting-edge technology with a relaxed, welcoming atmosphere.',
  ARRAY['Digital X-Ray', 'Interest-free Finance', 'Late Appointments', 'WiFi', 'Music & TV'],
  '{"monday": "8:00-20:00", "tuesday": "8:00-20:00", "wednesday": "8:00-20:00", "thursday": "8:00-20:00", "friday": "8:00-18:00", "saturday": "9:00-14:00", "sunday": "Closed"}'::jsonb,
  true,
  true,
  false,
  false,
  true
),
(
  'Clapham Family Dentist',
  '45 Clapham High Street',
  'SW4 7UR',
  51.4627,
  -0.1386,
  '020 7622 3454',
  'info@claphamfamilydentist.co.uk',
  'https://claphamfamilydentist.co.uk',
  4.6,
  156,
  ARRAY['General Dentistry', 'Dental Implants', 'Teeth Whitening', 'Children''s Dentistry', 'Emergency Care'],
  'mid',
  'Established family practice serving Clapham for over 20 years. NHS and private treatments with flexible payment options.',
  ARRAY['NHS Available', 'Child Friendly', 'Emergency Care', 'Payment Plans', 'Parking', 'Wheelchair Access'],
  '{"monday": "9:00-18:00", "tuesday": "9:00-18:00", "wednesday": "9:00-18:00", "thursday": "9:00-19:00", "friday": "9:00-17:00", "saturday": "9:00-13:00", "sunday": "Closed"}'::jsonb,
  false,
  true,
  true,
  true,
  true
),
(
  'Chelsea Dental Aesthetics',
  '78 King''s Road, Chelsea',
  'SW3 4UD',
  51.4883,
  -0.1692,
  '020 7352 8228',
  'enquiries@chelseadental.co.uk',
  'https://chelseadental.co.uk',
  4.9,
  178,
  ARRAY['Veneers', 'Invisalign', 'Composite Bonding', 'Teeth Whitening', 'Dental Implants'],
  'premium',
  'Boutique dental practice on King''s Road specializing in high-end cosmetic dentistry and smile design.',
  ARRAY['VIP Service', 'Sedation Options', 'Same-day Treatments', 'Digital Smile Design', 'Concierge Service'],
  '{"monday": "8:30-18:00", "tuesday": "8:30-18:00", "wednesday": "8:30-18:00", "thursday": "8:30-19:00", "friday": "8:30-17:00", "saturday": "10:00-16:00", "sunday": "Closed"}'::jsonb,
  true,
  true,
  false,
  true,
  true
),
(
  'The London Dental Centre',
  '109 Lever Street, Islington',
  'EC1V 3RQ',
  51.5272,
  -0.0957,
  '020 3667 7070',
  'info@thelondondentalcentre.co.uk',
  'https://thelondondentalcentre.co.uk',
  5.0,
  256,
  ARRAY['Invisalign', 'Dental Implants', 'Composite Bonding', 'Teeth Whitening', 'Airflow Polish', 'Veneers', 'General Dentistry', 'Hygiene Clean', 'Fillings', 'Emergency Care'],
  'mid',
  'Caring, holistic and cosmetic dentistry for the whole of London. We provide the best treatment available for comprehensive general & cosmetic dentistry. Located in Islington, minutes from Angel and Old Street stations.',
  ARRAY['Digital X-Ray', '3D Planning', 'Same-day Emergency', 'Interest-free Finance', 'Sedation Available', 'Dental Insurance Accepted', 'WiFi', 'Late Appointments', 'Weekend Appointments'],
  '{"monday": "9:00-19:00", "tuesday": "9:00-19:00", "wednesday": "9:00-19:00", "thursday": "9:00-19:00", "friday": "9:00-18:00", "saturday": "10:00-16:00", "sunday": "Closed"}'::jsonb,
  true,
  true,
  false,
  false,
  true
)
ON CONFLICT DO NOTHING;
